"""
Database access layer for listing_tasks table.

Following Context7 best practices for Supabase CRUD operations.
"""

from typing import Optional
from datetime import datetime
from fastapi import HTTPException
from postgrest.exceptions import APIError

from backend.database.supabase_client import get_supabase_client
from backend.models.listing_task import (
    ListingTaskCreate,
    ListingTaskUpdate,
    ListingTask,
    ListingTaskListResponse,
    TaskStatus,
    TaskCategory,
    VisibilityGroup
)


async def create_listing_task(task_data: ListingTaskCreate, task_id: str) -> ListingTask:
    """
    Create a new listing task.

    Args:
        task_data: Task data from request
        task_id: ULID generated by the caller

    Returns:
        Created listing task

    Raises:
        HTTPException: 409 if duplicate, 500 if database error
    """
    db = get_supabase_client()

    try:
        data = task_data.model_dump()
        data["task_id"] = task_id

        response = db.table("listing_tasks").insert(data).execute()

        if not response.data:
            raise HTTPException(
                status_code=500,
                detail="Failed to create listing task"
            )

        return ListingTask(**response.data[0])

    except APIError as e:
        if "duplicate key" in str(e).lower():
            raise HTTPException(
                status_code=409,
                detail="Listing task with this ID already exists"
            )
        if "foreign key" in str(e).lower():
            raise HTTPException(
                status_code=400,
                detail="Invalid listing_id, realtor_id, or assigned_staff_id"
            )
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_listing_task_by_id(task_id: str) -> Optional[ListingTask]:
    """
    Get a listing task by ID.

    Args:
        task_id: Task ID to retrieve

    Returns:
        Listing task if found, None otherwise
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("listing_tasks")
            .select("*")
            .eq("task_id", task_id)
            .is_("deleted_at", "null")
            .execute()
        )

        if not response.data:
            return None

        return ListingTask(**response.data[0])

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def list_listing_tasks(
    listing_id: Optional[str] = None,
    realtor_id: Optional[str] = None,
    assigned_staff_id: Optional[str] = None,
    status: Optional[TaskStatus] = None,
    task_category: Optional[TaskCategory] = None,
    visibility_group: Optional[VisibilityGroup] = None,
    limit: int = 50,
    offset: int = 0
) -> ListingTaskListResponse:
    """
    List listing tasks with optional filters.

    Args:
        listing_id: Filter by listing
        realtor_id: Filter by realtor
        assigned_staff_id: Filter by assigned staff
        status: Filter by task status
        task_category: Filter by category
        visibility_group: Filter by visibility group
        limit: Maximum number of results (default 50)
        offset: Number of results to skip (default 0)

    Returns:
        List of listing tasks with pagination metadata
    """
    db = get_supabase_client()

    try:
        # Build query
        query = db.table("listing_tasks").select("*", count="exact").is_("deleted_at", "null")

        # Apply filters
        if listing_id:
            query = query.eq("listing_id", listing_id)
        if realtor_id:
            query = query.eq("realtor_id", realtor_id)
        if assigned_staff_id:
            query = query.eq("assigned_staff_id", assigned_staff_id)
        if status:
            query = query.eq("status", status.value)
        if task_category:
            query = query.eq("task_category", task_category.value)
        if visibility_group:
            query = query.eq("visibility_group", visibility_group.value)

        # Apply pagination and ordering
        query = query.order("created_at", desc=True).range(offset, offset + limit - 1)

        response = query.execute()

        tasks = [ListingTask(**item) for item in response.data]
        total = response.count or 0

        return ListingTaskListResponse(
            tasks=tasks,
            total=total,
            limit=limit,
            offset=offset
        )

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def update_listing_task(task_id: str, task_data: ListingTaskUpdate) -> ListingTask:
    """
    Update a listing task.

    Args:
        task_id: Task ID to update
        task_data: Fields to update

    Returns:
        Updated listing task

    Raises:
        HTTPException: 404 if not found, 500 if database error
    """
    db = get_supabase_client()

    try:
        # Filter out None values
        data = {k: v for k, v in task_data.model_dump().items() if v is not None}

        if not data:
            # No fields to update, just return current task
            task = await get_listing_task_by_id(task_id)
            if not task:
                raise HTTPException(
                    status_code=404,
                    detail="Listing task not found"
                )
            return task

        response = (
            db.table("listing_tasks")
            .update(data)
            .eq("task_id", task_id)
            .is_("deleted_at", "null")
            .execute()
        )

        if not response.data:
            raise HTTPException(
                status_code=404,
                detail="Listing task not found"
            )

        return ListingTask(**response.data[0])

    except APIError as e:
        if "foreign key" in str(e).lower():
            raise HTTPException(
                status_code=400,
                detail="Invalid realtor_id or assigned_staff_id"
            )
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def soft_delete_listing_task(task_id: str) -> bool:
    """
    Soft delete a listing task (sets deleted_at timestamp).

    Args:
        task_id: Task ID to delete

    Returns:
        True if deleted, False if not found

    Raises:
        HTTPException: 500 if database error
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("listing_tasks")
            .update({"deleted_at": datetime.utcnow().isoformat()})
            .eq("task_id", task_id)
            .is_("deleted_at", "null")
            .execute()
        )

        return len(response.data) > 0

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_listing_tasks_by_listing(listing_id: str) -> list[ListingTask]:
    """
    Get all non-deleted tasks for a specific listing.

    Args:
        listing_id: Listing ID to get tasks for

    Returns:
        List of listing tasks
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("listing_tasks")
            .select("*")
            .eq("listing_id", listing_id)
            .is_("deleted_at", "null")
            .order("created_at", desc=True)
            .execute()
        )

        return [ListingTask(**item) for item in response.data]

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_listing_tasks_by_realtor(realtor_id: str) -> list[ListingTask]:
    """
    Get all non-deleted tasks for a specific realtor.

    Args:
        realtor_id: Realtor ID to get tasks for

    Returns:
        List of listing tasks
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("listing_tasks")
            .select("*")
            .eq("realtor_id", realtor_id)
            .is_("deleted_at", "null")
            .order("created_at", desc=True)
            .execute()
        )

        return [ListingTask(**item) for item in response.data]

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_listing_tasks_by_staff(staff_id: str) -> list[ListingTask]:
    """
    Get all non-deleted tasks assigned to a specific staff member.

    Args:
        staff_id: Staff ID to get tasks for

    Returns:
        List of listing tasks
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("listing_tasks")
            .select("*")
            .eq("assigned_staff_id", staff_id)
            .is_("deleted_at", "null")
            .order("created_at", desc=True)
            .execute()
        )

        return [ListingTask(**item) for item in response.data]

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )
