"""
Database access layer for stray_tasks table.

Following Context7 best practices for Supabase CRUD operations.
"""

from typing import Optional
from datetime import datetime
from fastapi import HTTPException
from postgrest.exceptions import APIError

from backend.database.supabase_client import get_supabase_client
from backend.models.stray_task import (
    StrayTaskCreate,
    StrayTaskUpdate,
    StrayTask,
    StrayTaskListResponse,
    TaskStatus
)


async def create_stray_task(task_data: StrayTaskCreate, task_id: str) -> StrayTask:
    """
    Create a new stray task.

    Args:
        task_data: Task data from request
        task_id: ULID generated by the caller

    Returns:
        Created stray task

    Raises:
        HTTPException: 409 if duplicate, 500 if database error
    """
    db = get_supabase_client()

    try:
        data = task_data.model_dump()
        data["task_id"] = task_id

        response = db.table("stray_tasks").insert(data).execute()

        if not response.data:
            raise HTTPException(
                status_code=500,
                detail="Failed to create stray task"
            )

        return StrayTask(**response.data[0])

    except APIError as e:
        if "duplicate key" in str(e).lower():
            raise HTTPException(
                status_code=409,
                detail="Stray task with this ID already exists"
            )
        if "foreign key" in str(e).lower():
            raise HTTPException(
                status_code=400,
                detail="Invalid realtor_id or assigned_staff_id"
            )
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_stray_task_by_id(task_id: str) -> Optional[StrayTask]:
    """
    Get a stray task by ID.

    Args:
        task_id: Task ID to retrieve

    Returns:
        Stray task if found, None otherwise
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("stray_tasks")
            .select("*")
            .eq("task_id", task_id)
            .is_("deleted_at", "null")
            .execute()
        )

        if not response.data:
            return None

        return StrayTask(**response.data[0])

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_stray_task_by_key(realtor_id: str, task_key: str) -> Optional[StrayTask]:
    """
    Get a stray task by realtor_id and task_key combination.

    Args:
        realtor_id: Realtor ID
        task_key: Task key (classification identifier)

    Returns:
        Stray task if found, None otherwise
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("stray_tasks")
            .select("*")
            .eq("realtor_id", realtor_id)
            .eq("task_key", task_key)
            .is_("deleted_at", "null")
            .execute()
        )

        if not response.data:
            return None

        return StrayTask(**response.data[0])

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def list_stray_tasks(
    realtor_id: Optional[str] = None,
    assigned_staff_id: Optional[str] = None,
    status: Optional[TaskStatus] = None,
    task_key: Optional[str] = None,
    limit: int = 50,
    offset: int = 0
) -> StrayTaskListResponse:
    """
    List stray tasks with optional filters.

    Args:
        realtor_id: Filter by realtor
        assigned_staff_id: Filter by assigned staff
        status: Filter by task status
        task_key: Filter by task key
        limit: Maximum number of results (default 50)
        offset: Number of results to skip (default 0)

    Returns:
        List of stray tasks with pagination metadata
    """
    db = get_supabase_client()

    try:
        # Build query
        query = db.table("stray_tasks").select("*", count="exact").is_("deleted_at", "null")

        # Apply filters
        if realtor_id:
            query = query.eq("realtor_id", realtor_id)
        if assigned_staff_id:
            query = query.eq("assigned_staff_id", assigned_staff_id)
        if status:
            query = query.eq("status", status.value)
        if task_key:
            query = query.eq("task_key", task_key)

        # Apply pagination and ordering
        query = query.order("created_at", desc=True).range(offset, offset + limit - 1)

        response = query.execute()

        tasks = [StrayTask(**item) for item in response.data]
        total = response.count or 0

        return StrayTaskListResponse(
            tasks=tasks,
            total=total,
            limit=limit,
            offset=offset
        )

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def update_stray_task(task_id: str, task_data: StrayTaskUpdate) -> StrayTask:
    """
    Update a stray task.

    Args:
        task_id: Task ID to update
        task_data: Fields to update

    Returns:
        Updated stray task

    Raises:
        HTTPException: 404 if not found, 500 if database error
    """
    db = get_supabase_client()

    try:
        # Filter out None values
        data = {k: v for k, v in task_data.model_dump().items() if v is not None}

        if not data:
            # No fields to update, just return current task
            task = await get_stray_task_by_id(task_id)
            if not task:
                raise HTTPException(
                    status_code=404,
                    detail="Stray task not found"
                )
            return task

        response = (
            db.table("stray_tasks")
            .update(data)
            .eq("task_id", task_id)
            .is_("deleted_at", "null")
            .execute()
        )

        if not response.data:
            raise HTTPException(
                status_code=404,
                detail="Stray task not found"
            )

        return StrayTask(**response.data[0])

    except APIError as e:
        if "foreign key" in str(e).lower():
            raise HTTPException(
                status_code=400,
                detail="Invalid realtor_id or assigned_staff_id"
            )
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def soft_delete_stray_task(task_id: str) -> bool:
    """
    Soft delete a stray task (sets deleted_at timestamp).

    Args:
        task_id: Task ID to delete

    Returns:
        True if deleted, False if not found

    Raises:
        HTTPException: 500 if database error
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("stray_tasks")
            .update({"deleted_at": datetime.utcnow().isoformat()})
            .eq("task_id", task_id)
            .is_("deleted_at", "null")
            .execute()
        )

        return len(response.data) > 0

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_stray_tasks_by_realtor(realtor_id: str) -> list[StrayTask]:
    """
    Get all non-deleted stray tasks for a specific realtor.

    Args:
        realtor_id: Realtor ID to get tasks for

    Returns:
        List of stray tasks
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("stray_tasks")
            .select("*")
            .eq("realtor_id", realtor_id)
            .is_("deleted_at", "null")
            .order("created_at", desc=True)
            .execute()
        )

        return [StrayTask(**item) for item in response.data]

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_stray_tasks_by_staff(staff_id: str) -> list[StrayTask]:
    """
    Get all non-deleted stray tasks assigned to a specific staff member.

    Args:
        staff_id: Staff ID to get tasks for

    Returns:
        List of stray tasks
    """
    db = get_supabase_client()

    try:
        response = (
            db.table("stray_tasks")
            .select("*")
            .eq("assigned_staff_id", staff_id)
            .is_("deleted_at", "null")
            .order("created_at", desc=True)
            .execute()
        )

        return [StrayTask(**item) for item in response.data]

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )


async def get_open_stray_tasks(realtor_id: Optional[str] = None) -> list[StrayTask]:
    """
    Get all open (not completed/cancelled) stray tasks.

    Args:
        realtor_id: Optional filter by realtor

    Returns:
        List of open stray tasks
    """
    db = get_supabase_client()

    try:
        query = (
            db.table("stray_tasks")
            .select("*")
            .is_("deleted_at", "null")
            .in_("status", ["OPEN", "CLAIMED", "IN_PROGRESS"])
        )

        if realtor_id:
            query = query.eq("realtor_id", realtor_id)

        response = query.order("created_at", desc=True).execute()

        return [StrayTask(**item) for item in response.data]

    except APIError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {str(e)}"
        )
